; T5 4.7" E-Paper V2.3 (ESP32-S3) E-Reader Firmware
; Board: LILYGO T5-ePaper-S3 with ED047TC1 display

[env:lilygo-t5-47-s3]
platform = espressif32@6.4.0
board = lilygo_t5_47_s3_n16r8
framework = arduino

board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_size = 16MB
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_build.partitions = partitions.csv

monitor_speed = 115200
upload_speed = 921600

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCONFIG_SPIRAM_MODE_OCT=1
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_LOOP_STACK_SIZE=16384


lib_deps =
    https://github.com/Xinyuan-LilyGO/LilyGo-EPD47.git#esp32s3
    lewisxhe/SensorLib@^0.2.0
    bblanchon/ArduinoJson@^6
    https://github.com/bitbank2/JPEGDEC.git
    https://github.com/bitbank2/PNGdec.git
    https://github.com/leethomason/tinyxml2.git#10.0.0
    ricmoo/QRCode@^0.0.1

lib_ldf_mode = deep+

[env:gh_release]
extends = env:lilygo-t5-47-s3
build_flags =
    ${env:lilygo-t5-47-s3.build_flags}
    -DFIRMWARE_VERSION='"${sysenv.RELEASE_TAG}"'
